### ISSUE TITLE
Data formats

### ISSUE THREAD

**Issue by palango** [PaweX/NewSettlers4Project#2]
Do you have any information about the used data formats?

**Comment by PaweX** [comment]
Unfortunately not, but I heard somebody claims to have them. However I haven't contacted that person yet. He is doing different project at the moment.
However if you know something tell me please. I focus on game designing rather than programming. This project is an open proposition to start making a free clone of Settlers IV, I know there are people who tried to do some things on their own, but this can only work when we work together (like it happened with the jsettlers project).

**Comment by palango** [comment]
> Unfortunately not, but I heard somebody claims to have them. However I haven't contacted that person yet. He is doing different project at the moment.

Can you contact that person or link her/him here?

**Comment by PaweX** [comment]
You knew the right time to write here, because I wasn't here for a few months ;).

Ok, we can try to ask him, but it looks like he didn't do anything with Settlers recently. Somebody asked him very similar question like you asked but he has never replied or at least officially. He made the map loading system for the jsettlers.

**Comment by PaweX** [comment]
@tomsoftware are you still working on Settlers IV project? Is there any possibility that you may share anything you have found?

_I know at least a few people that would be interested about being involved in such project like open S4. A group of people can make something - like it happened with jsettlers. These games are timeless._

**Comment by tomsoftware** [comment]
yes, I'm now able to decompress all data-files (config, maps, savegames, ...) and display the image files. My aim is to create a web-game (webgl for graphic, logic in typescript) - like my lemmings.ts project. Problme: to less time, too much projects.

**Comment by tomsoftware** [comment]
I publisched my "research" results about the file formats used by Settlers 4 at https://github.com/tomsoftware/Settlers.ts

**Comment by PaweX** [comment]
Yes, time can be a big issue, I didn't have it much as well :/ .
Thanks for all of your work @tomsoftware !
I will have a look at the link more closely later. I was always curious how the maps are saved and if it is possible to convert savegame files to map files.

Do you know if the graphics engine from S3 (I am thinking about e.g. jsettlers) can be modified and reused in S4? I am thinking yes, but you will probably know better how similar they are.
